DROP DATABASE IF EXISTS TrafficMonitoring;

CREATE DATABASE TrafficMonitoring;

USE TrafficMonitoring;

CREATE TABLE VESSEL(
    IMO INT NOT NULL,
	Flag CHAR(30),
	Name VARCHAR(128),
	Built SMALLINT,
	CallSign VARCHAR(20),
	Length SMALLINT,
	Breadth SMALLINT,
    Tonnage MEDIUMINT,
	MMSI INT,
    Type VARCHAR(60),
    Status VARCHAR(40),
	Owner SMALLINT,
    PRIMARY KEY(IMO)
);

LOAD DATA INFILE './PermanentData/VESSEL.csv' INTO TABLE VESSEL COLUMNS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE MAP_VIEW(
    Id MEDIUMINT NOT NULL,
    ICESNAME VARCHAR(20),
    West DECIMAL(4,2),
    South DECIMAL(4,2),
    East DECIMAL(4,2),
    North DECIMAL(4,2),
    Scale SMALLINT,
    FileName VARCHAR(20),
    ImageWidth SMALLINT,
    ImageHeigth SMALLINT,
    ImageWest DECIMAL(4,2),
    ImageSouth DECIMAL(8,6),
    ImageEast DECIMAL(4,2),
    ImageNorth DECIMAL(8,6),
    ContainerRectangle SMALLINT,
    PRIMARY KEY(Id)
);

LOAD DATA INFILE './PermanentData/MAP_VIEW.csv' INTO TABLE MAP_VIEW COLUMNS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE PORT(
    Id INT,
    LOCODE VARCHAR(10),
    Port_Location VARCHAR(50),
    Country VARCHAR(50),
    Longitude DECIMAL(9,6),
    Latitude DECIMAL(9,6),
    Web_Site VARCHAR(50),
    MapView_1_Id MEDIUMINT,
    MapView_2_Id MEDIUMINT,
    MapView_3_Id MEDIUMINT,
    FOREIGN KEY(MapView_1_Id) REFERENCES MAP_VIEW(Id),
    FOREIGN KEY(MapView_2_Id) REFERENCES MAP_VIEW(Id),
    FOREIGN KEY(MapView_3_Id) REFERENCES MAP_VIEW(Id),
    PRIMARY KEY(Id)
);

LOAD DATA INFILE './PermanentData/PORT.csv' INTO TABLE PORT COLUMNS TERMINATED BY ';' IGNORE 1 ROWS;

CREATE TABLE AIS_MESSAGE(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    AIS_Timestamp DATETIME,
    Class VARCHAR(20),
    MMSI INT,
    MsgType VARCHAR(50),
    PRIMARY KEY(Id)
);

CREATE TABLE POSITION_REPORT(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    Type VARCHAR(60),
    Latitude DECIMAL(9,6),
    Longitude DECIMAL(9,6),
    Status VARCHAR(60),
    RoT DECIMAL(5,2),
    SoG DECIMAL(5,2),
    CoG DECIMAL(5,2),
    Heading MEDIUMINT,
    PRIMARY KEY(Id),
    FOREIGN KEY(Id) REFERENCES AIS_MESSAGE(Id) ON DELETE CASCADE
);

CREATE TABLE STATIC_DATA(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    IMO INT,
    CallSign VARCHAR(20),
    Name VARCHAR(128),
    Vessel_Type VARCHAR(60),
    Cargo_Type VARCHAR(60),
    Length SMALLINT,
    Breadth SMALLINT,
    Draught DECIMAL(5, 2),
    AIS_Destination VARCHAR(20),
    ETA DATETIME,
    A SMALLINT,
    B SMALLINT,
    C SMALLINT,
    D SMALLINT,
    PRIMARY KEY(Id),
    FOREIGN KEY(Id) REFERENCES AIS_MESSAGE(Id) ON DELETE CASCADE
);